config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  patch 'tasks/:id', to: 'tasks#update'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <%= form_for(@task) do |t| %>
    <%= t.label :title %>
    <%= t.text_field :title %>
    <%= t.label :details  %>
    <%= t.text_field :details %>
    <%= t.submit "Update Task" %>
    Completed:
    <%= t.radio_button :completed, :checked => true %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="container" >
  <h1>Tasks:</h1>

  <ol>
      <% @tasks.each do |t| %>
        <li>
          <%= link_to t.title, task_path(t) %>
        </li>
      <% end %>
  </ol>

  <%= link_to "New Task", new_task_path  %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <%= form_for(@task) do |t| %>
    <%= t.label :title %>
    <%= t.text_field :title %>
    <%= t.label :details  %>
    <%= t.text_field :details %>
    <%= t.submit "Create New Task" %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1>Task:</h1>

  <div>
    <%= @task.title %>
  </div>
  <div>
    <h3>Details:</h3>
    <%= @task.details %>
  </div>
  <br>
  <%= link_to "Edit this Task", edit_task_path  %>
  <br>
  <%= link_to "Back to Tasks", tasks_path  %>
  <br>
  <%= link_to "Delete task", delete_task_path(@task), method: :delete %>
</div>